### ISSUE TITLE
Publisher isn't emmiting a "publish" request for media stream event on websocket

### ISSUE THREAD

**Issue by 90felipe09** [kevin29a/angular-janus#5] opened 2020-12-02 12:16 UTC
First of all, thank you very much @kevin29a for this awesome project. You can't imagine how grateful i am for this initiative of yours. A great work indeed.

Now for the issue. I configured the janus-videoroom component to implement a functioning videoroom and i'm connecting with my own janus server with WSS. I managed to connect this component with the public test videoroom from meetecho, but i noticed that i was able to fetch the published media from other users that were present in the public videoroom, but i wasn't publishing my media to them. It's important to say that i gave the appropriate permissions for my browser to access my media devices, so it's not the actual issue.

By verifying the steps that the component was performing from the protocol for the video room use case, i've noticed that the last request made was "join" request. That was a succesful request since i've got a 'joined' response. But after that the only requests made has been 'keep alive' requests with 'ack' responses. I know that to effectively publish my media stream it should have made a 'publish' request.

I'd like to know how to solve this issue. It's something that i skipped in configuration of the component?

I will provide more information if needed.

Thank you very much in advance. Keep it up with this awesome project. I'm grateful for your work.

Cheers.

**Comment by kevin29a** [comment] 2020-12-02 19:14
Hey, sounds like a bug. What browser are you on? Do you see any errors in the console log?

It's possible to join a room in listener only mode by passing `[role]='JanusRole.listener` to the janus-videoroom component. You can explicitly pass `[role]='JanusRole.publisher`. However, the default is publisher, so I don't think that's the problem.

**Comment by 90felipe09** [comment] 2020-12-02 19:39
Oh, hi Kevin. Thanks for the fast answer.

About logs in console: No. There are no exceptions popping.

About the role issue: i'm already passing explicit values for it as JanusRole.publisher. When verifying the sessions created through the admin in the janus server i see that it has been created correctly as a publisher role. So i wouldn't point the role wrong value attribution as the cause.

About being wrong server configuration: I tested by pointing to the meetecho public videorooms and also pointing to my own janus server. The issue is the same. There is no 'publish' request being made so no way that the component is being able to stream it's attributed media.

About having unavailable devices: I've consolled.logged the devices that i'm feeding the component. They aren't null. They are valid media devices id's. I also tested by not passing them explicitly in order to let the component use the default devices, but in the end the results were the same.

About my browser: Currently using on mozilla firefox.

**Comment by kevin29a** [comment] 2020-12-02 19:45
Great. Thanks for the info. We haven't tested as extensively on firefox. Can you try on chrome real quick? That will give us a big hint as to where the issue is coming from.

**Comment by 90felipe09** [comment] 2020-12-02 19:55
Yes, i can test with chrome. May i deliver the results tomorrow? I'm not in the office anymore :(

**Comment by kevin29a** [comment] 2020-12-02 20:11
Sure thing.

**Comment by 90felipe09** [comment] 2020-12-03 17:10
Hello again. I tested it on Google chrome, and as you said, it works on chrome. It manages to send the 'configure' request (instead of 'publish', but in the end it's for the same purpose, to publish media to a janus server).

But as we now know, there is an issue with mozilla firefox here. What in terms of implementation that could be causing this issue?

Ah another thing that i've noticed, i tried sending role as JanusRole.listener instead of publisher just for testing, but it's sending a publisher role request instead. I've checked on the janus admin and indeed it's registering as a publisher role. Maybe the component is missing the overwrite of the default role in the request.

**Comment by kevin29a** [comment] 2020-12-03 21:22
We'll look into the firefox bug immediately. Should have a fix out by end of the week.

Regarding the listener, we always create a publisher handle regardless of whether you're publishing or not. We don't use that handle to publish a feed if you pass in "listener" as the role.

The "publisher" handle is a bit of confusing nomenclature imo. Even if you're just subscribing, there are good reasons to create the publisher handle. For example, if there's a pin on the room and require_pvtid is set to true, you must create the publisher handle first or you won't be able to subscribe. The publisher handle also receives events when other publishers join/leave the room. As such, we always create one even if we're not planning to publish a feed. I think it would be a better name if it was called the "control handle" or something like that.

**Comment by kevin29a** [comment] 2020-12-04 05:16
Just pushed a new version to npm. This fixes _a_ bug where firefox would not publish correctly. It's probably your bug, but won't know for sure until you test it. Let me know here and I'll close this out.

**Comment by 90felipe09** [comment] 2020-12-04 14:33
Hi @kevin29a, You were right. The new release v0.15.0 fixed the issue for mozilla firefox. That was awesome.

This project has a channel for donations like paypal? I think that it's fair supporting this project.

**Comment by kevin29a** [comment] 2020-12-04 16:26
OK, great. I'm going to close this out. We gratefully accept donations [here](https://www.paypal.com/donate?hosted_button_id=F88QF46FGCGUY).

**Closed as completed by kevin29a** 2020-12-04 16:26 UTC
